### ISSUE TITLE
use builtin method __str__

### ISSUE THREAD

**Issue by ch3p4ll3** [Thepowa753/OpenFoodFacts_Barcode#1]
https://github.com/Thepowa753/OpenFoodFacts_Barcode/blob/22cfb725270f236ed88b7357f9cf527dcebcae9b/dto/FoodDto.py#L34

**Comment by Thepowa753** [comment]
fixed with:
fca76b7249f18c1b9ed5f77bf5b1197484da066e


(to mare dio bon)
